### ISSUE TITLE
Solicitud de Feature: Implementación de un Builder para la clase Warrior

### ISSUE THREAD

**Issue by Javigfw** [DainWs/Crazy-Random-Multiverse#16]
Me gustaría solicitar la implementación de un Builder para la clase Warrior. Considero que esta funcionalidad facilitaría la realización de pruebas y verificación en futuros proyectos. Además, permitiría una mayor flexibilidad y claridad al instanciar objetos de esta clase.

Agradezco de antemano su consideración.

Gracias por su atención.

**Comment by DainWs** [comment]
Thanks to [@Javigfw](https://github.com/Javigfw) for the great idea!
